### ISSUE TITLE
Crash during compilation on JDK 8 when using JSpecify 0.3.0-alpha-1

### ISSUE THREAD

**Issue by msridhar** [jspecify/jspecify#302]
NullAway branch is here:

https://github.com/uber/NullAway/tree/update-jspecify

This is the crash (see [here](https://github.com/uber/NullAway/actions/runs/3211107300/jobs/5249041667)), which comes when running `./gradlew :test-java-lib:compileJava` on a JDK 8 JVM:

```
warning: unknown enum constant java.lang.annotation.ElementType.MODULE
warning: unknown enum constant java.lang.annotation.ElementType.MODULE
An exception has occurred in the compiler (1.8.0_345). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.code.TypeAnnotations.annotationType(TypeAnnotations.java:231)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:294)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitMethodDef(TypeAnnotations.java:1066)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.scan(TypeAnnotations.java:275)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
```

From #34 I can't tell if this was intended or not.  Do we not support using JSpecify annotations when building on JDK 8?  Building on JDK 8 is not a requirement for NullAway (we're planning to remove JDK 8 support soon); I am just wondering if this was intentional.

**Comment by msridhar** [comment]
FWIW a possible difference between this and previous test cases is that the code being compiled uses `@NullMarked` and `@NullUnmarked` on methods:

https://github.com/uber/NullAway/blob/e1ea7f62e8c82fe578e1c18446827849dad76c39/test-java-lib/src/main/java/com/example/jspecify/unannotatedpackage/Methods.java

**Comment by msridhar** [comment]
After further thought I realized we probably want to have NullAway support JDK 8 for some time longer, to support more open-source projects that haven't updated. So having JSpecify support building with JDK 8 would be helpful to us.

**Comment by cpovirk** [comment]
Oh, this is a good place to recall that [`MODULE` makes annotations usable _elsewhere_ under some versions of javac](https://github.com/jspecify/jspecify/issues/34#issuecomment-1209894688). That is a small and gross but practical reason to avoid it on the main annotation. It would also be a reason for tools to more carefully validate the locations on which annotations appear... which in turn could make the no-`@Target` approach more appealing, if only that approach, you know, _worked_ :)

**Comment by msridhar** [comment]
Thanks so much for investigating, @cpovirk.  I have one question.  Based on the stack trace and error message, I don't think this crash in JDK 8 javac is intended behavior.  Also it looks like one can at least still backport fixes to JDK 8 for future patch releases.  Here is the line of code throwing the assertion error:

https://github.com/openjdk/jdk8u-dev/blob/d285382278fcb76ceddfb61cf8bb047ff269de44/langtools/src/share/classes/com/sun/tools/javac/code/TypeAnnotations.java#L231

I wonder if we could submit a PR that changes this assertion to something less crash-y?  Like maybe emit another warning instead for an unknown enum constant?  Then at least this issue could be fixed in a future JDK 8 release, which gives us more options (like leaving things the way they are and telling users to update their JDK 8 release).  Of course this doesn't help with working around the current crash.

It looks like someone submitted an issue on this before:

https://bugs.openjdk.org/browse/JDK-8279557

They didn't have a reproducer so it got closed, but we have one now.  If we think it's worthwhile, I can try to re-open that issue or submit a new one, to see if we get feedback on the possibility of a change.  Let me know if we think that's worth a try.

**Comment by cpovirk** [comment]
Thank you! That is a better thought than any of the thoughts in my post :)

It does seem likely that upstream would like the compiler to not _crash_, regardless of how strange the code we feed it is.

It's possible that they could respond by changing the crash into a more normal but still fatal error, or it's possible that they don't deem this fix worth backporting. But maybe they'll see the value in making it easier for libraries to use the `MODULE` target. (As noted in #245, we tried solving this problem with multi-release jars instead. But [it's not clear if multi-release jars are supposed to solve this problem](https://github.com/jspecify/jspecify/issues/34#issuecomment-876595861), and regardless, [they don't under some major tools today](https://github.com/jspecify/jspecify/issues/245).)

Reproducing does look easy. If you're up for taking things to upstream, that would be terrific.

```java
$ tail -n +1 *.java 
==> A.java <==
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.MODULE;

import java.lang.annotation.Target;

@Target({METHOD, MODULE})
@interface A {}

==> B.java <==
class B {
  @A void b() {}
}
```

```
$ $HOME/openjdk-11.0.16/bin/javac -source 8 -target 8 -sourcepath doesnotexist A.java && $HOME/openjdk-8u342/bin/javac -cp . -sourcepath doesnotexist B.java
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
warning: unknown enum constant ElementType.MODULE
An exception has occurred in the compiler (1.8.0_342). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.SharedNameTable$NameImpl)
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.code.TypeAnnotations.annotationType(TypeAnnotations.java:231)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:294)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitMethodDef(TypeAnnotations.java:1066)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.scan(TypeAnnotations.java:275)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitClassDef(TypeAnnotations.java:1042)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.scan(TypeAnnotations.java:275)
        at com.sun.tools.javac.code.TypeAnnotations$1.run(TypeAnnotations.java:127)
        at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:152)
        at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:857)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)
```
```

**Comment by msridhar** [comment]
I will report this upstream and then report back.  Let's hope for a positive response :-)

**Comment by msridhar** [comment]
The bug report got created:

https://bugs.openjdk.org/browse/JDK-8295314

However, it got erroneously closed as "Cannot reproduce" because the repro instructions were not followed correctly (JDK 17 was used to compile `B.java`).

I will try to use the "submit additional info" link to clarify.  But @cpovirk @kevinb9n if we know someone with a JDK bug system account who could comment directly, that might be more effective.

**Comment by cpovirk** [comment]
Thanks. I think @eamonnmcmanus said that he had The Power? Éamonn, are you up for it?

**Comment by eamonnmcmanus** [comment]
I do indeed have an openjdk.org account. Let me know if "submit additional info" doesn't produce the desired results and I can comment on the bug.

**Comment by msridhar** [comment]
Update: it looks like "submit additional info" worked as [the bug](https://bugs.openjdk.org/browse/JDK-8295314) has been re-opened.  Not sure who would look at this / prioritize it.  I'll wait a bit and see what happens.

**Comment by msridhar** [comment]
For those familiar with the JDK bug reporting process: is there any way to know if [JDK-8295314](https://bugs.openjdk.org/browse/JDK-8295314) has or will be triaged?  I am wondering how we can get the right eyes on it.  I think we have a good case that it's worth fixing, but probably we need someone involved with JDK 8 maintenance to see it for it to get noticed, and I'm not sure if that will happen automatically.

We're about to add a one-off `@NullUnmarked` annotation to a project because of this issue 😐

**Comment by msridhar** [comment]
Update: thanks to help from @cushon and @cpovirk, we discovered this bug still exists in the latest version of `javac` if you create a `.class` file for an annotation with an invalid `ElementType` in its `@Target` meta-annotation.  This has been filed as a new bug against JDK 19:

https://bugs.openjdk.org/browse/JDK-8296010

Our hope is that the new bug gets fixed in the latest Java version, and that eventually we can backport the fix all the way to JDK 8.

**Comment by cpovirk** [comment]
Trying to summarize where we are, which we discussed some in today's meeting:

- We'll of course want to document this incompatibility, along with the workaround of using a newer JDK to build with `--release 8` or similar (though that's [not _always_ trivial](https://github.com/google/guava/issues/3990)).
   - NEW: Maybe we can even recommend continuing to build with JDK8 but switching to use the JDK8-compatible javac9 codebase, as we do in Guava [for other reasons](https://github.com/google/guava/commit/6d7e326b2cbfba5f19fc67859c0b3d4c45fab63f#diff-f55fbe13c7adc434c330f6899bbfa6600eacdc386020546d1d6e393ca4a828f9R459)?
- Even once the incompatibility is fixed, we'll want to document that people need to upgrade to \<whichever JDK8 patch release\> to pick up the fix, _and_ we'll want to document that _`-Werror`_ will still be a no-no unless you upgrade to JDK9+.
- We should write something about our the versions of JDK and Android that we support more generally (build and runtime, with whatever caveats we need to give).
- There aren't any wildly appealing workarounds available on the JSpecify side:
  - A no-`@Target` annotation is supposed to be usable on `MODULE`, but it [currently isn't](https://github.com/jspecify/jspecify/issues/34#issuecomment-763026878). (And of course it is also usable in other locations that we _don't_ want it used on, even more so than [`MODULE` itself sometimes accidentally permits](https://github.com/jspecify/jspecify/issues/34#issuecomment-1209894688).)
  - Multi-release jars [don't currently help](https://github.com/jspecify/jspecify/issues/302#issuecomment-1273745773).
  - We could theoretically release two separate "versions" of 0.3.0, two separate "versions" of 1.0.0, etc. (continuing until we're willing to drop JDK8 support), similar to [how Guava releases `-android` and `-jre` "versions."](https://github.com/google/guava/wiki/Release22#new-android-version) One "version" would give the annotations a `MODULE` target; the other would not. No one loves that approach, but we have evidence that it """works""" for this kind of thing.
  - For each affected annotation, we could provide [two otherwise identical annotations with different `@Target` values](https://github.com/jspecify/jspecify/issues/302#issuecomment-1273575846) (e.g., `@NullMarked` and `@ModulelessNullMarked`. That would be a permanent wart, but it seems like it would also work.

**Comment by msridhar** [comment]
> * NEW: Maybe we can even recommend continuing to build with JDK8 but switching to use the JDK8-compatible javac9 codebase, as we do in Guava [for other reasons](https://github.com/google/guava/commit/6d7e326b2cbfba5f19fc67859c0b3d4c45fab63f#diff-f55fbe13c7adc434c330f6899bbfa6600eacdc386020546d1d6e393ca4a828f9R459)?

I really like this as a temporary workaround!  It's probably the least disruptive option for those who still need to build using JDK8.  I just used it to unblock https://github.com/uber/NullAway/pull/673 and get the build green on JDK 8 there.  And Error Prone's javac9 is battle tested and reliable.  Hopefully in the medium term, we will get a fix backported to JDK 8 so even this workaround is not needed.  And then the only remaining issue is not being able to compile with `-Werror` on JDK 8, which I think we'll just have to live with.

**Comment by kevinb9n** [comment]
> * We'll of course want to document 

This oughtta be mediocre enough to snipe you into editing it:
[../wiki/version-compatibility](wiki/version-compatibility)

**Comment by msridhar** [comment]
It looks like the MODULE target can also cause problems with javadoc:

https://github.com/wala/WALA/actions/runs/3634061250/jobs/6131766621#step:5:253

I see #351 actually removed `@Target(MODULE)` from `@NullUnmarked`.  @cpovirk any chance we could get an `0.3.0-alpha-3` release that includes this change?  It would save us from having to make a one-off `@NullUnmarked` annotation in WALA, where some configs still build on JDK 8.  I don't know of a simple Error-Prone-javac-based workaround for the javadoc crash.

**Comment by cpovirk** [comment]
Oh, thanks for that report. It would be nice if we had a workaround like you describe, but I'm not excited about trying to figure one out right now... :)

As it happens, I did release 0.3.0-alpha-3 (because I missed a problem with our module-info). And while I forgot to mention it in the initial release notes, it does additionallycontain the change you're looking for. I eventually noticed that and updated https://github.com/jspecify/jspecify/releases/tag/v0.3.0-alpha-3 to mention it.

**Comment by msridhar** [comment]
Thanks a lot @cpovirk I think the alpha 3 release should fix it!

**Comment by cpovirk** [comment]
Seen in the wild: https://stackoverflow.com/a/76254522/28465

I will continue feeling bad about this and _eventually_ do something about it.

**Comment by msridhar** [comment]
> Seen in the wild: https://stackoverflow.com/a/76254522/28465

If we ever get any further info, I'd be curious to know the use case for writing `@NullMarked` on a method (though of course it'd be better if we could just not cause `javac` to crash).

**Comment by SimY4** [comment]
Hello, everyone. Just stumbled upon this issue myself. Migrating my codebase away from JSR305 to jspecify and see that compiler raises a warning.

Not sure if that was discussed earlier, but have you considered using JDK 9 multi-release jars support? https://openjdk.org/jeps/238 TL;DR you can ship two versions of a class in a single jar. One for everything before Java 9 and then for every release of Java you can have it's own class file.

Essentially, for every release of jspecify you can ship two classfiles
1. One with Java 8 enum options for @Target
2. One with Java 9 enum options for @Target

Should mitigate the warning under Java 8 target and still support newer targets (even beyond Java 9).

**Comment by cpovirk** [comment]
Sorry, I lost track of this thread... among others recently... :(

We had tried a multi-release jar for this purpose a couple years ago, and it turns out that [it doesn't achieve that purpose](https://github.com/jspecify/jspecify/issues/245). The idea of a multi-release jar is that the _API_ of the classes is supposed to match across versions. The definition of "API" was left a little fuzzy AFAICT, but the idea seems to ([mostly?](https://github.com/jspecify/jspecify/issues/245#issuecomment-2004314981)) be that a compiler should be able to look at whichever version it wants. That means that we can't count on it to look at the version that contains `MODULE` in its `@Target`, and indeed multiple tools currently don't do that.

Or maybe the tools are buggy. Even if so, we probably don't want to take an approach that will cause problems for those tools in order to work around a problem with a tool (javac) that is probably at least easier to migrate off of (by upgrading to javac 9+, even while still targeting older versions of Java).

**Comment by cpovirk** [comment]
(But thank you for raising that suggestion! I wish that it had worked out....)

**Comment by cpovirk** [comment]
I should write down a clarification here, since I was missing it myself:

There are two distinct problems that the `@Target(MODULE, ...)` on `NullMarked` can cause:
1. `java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE`
2. `warning: unknown enum constant ElementType.MODULE`

(OK, users could _also_ have trouble [reading the `@Target` values at _runtime_ under Java 8](https://github.com/jspecify/jspecify/issues/245#issuecomment-1123271588), but that seems less likely to come up.)

This issue is nominally about (1) but for `Null`**`Unmarked`**. (It's true that the output in the first post of this issue _also_ contains the second warning, but the two problems are separable.) We have solved the problem for that annotation by removing `MODULE` from the target of that annotation. (That change doesn't reduce functionality: "Unmarked" is already the "default default." Thus, setting it explicitly on the module would always be a no-op.)

Problem (1) still exists for `NullMarked`, but note that it can arise only when you apply the annotation at the method level, not the class or package level. We don't expect it to be applied at the method level as often as the other two levels, but occasionally it will be.

Also note that problem (1) exists only when _building with a JDK 8 javac_. [Building with a newer JDK](https://github.com/jspecify/jspecify/issues/537), even when targeting an older version of Java (as with `--release 8`), does not trigger this problem. 

(We were able to get new versions of javac [changed](https://bugs.openjdk.org/browse/JDK-8296010) to produce a better error for unrecognized `@Target` values, rather than a crash. But that doesn't help people who build with JDK 8 at all—unless that change is someday backported, in which case their builds will _still_ fail but in a slightly nicer way :))

Then there's [problem (2)](https://github.com/google/truth/issues/1320). That problem exists not only under the JDK 8 javac but also under newer versions of javac _but_ only with `--release 8` and then only _sometimes_, notably with Error Prone. (The Error Prone problem began with a change I made that was released in Error Prone 2.20.0, but a fix will be coming in the next release, whether that's numbered 2.28.1 or 2.29.0. In the meantime, you can work around it by disabling the offending check with `-Xep:NullArgumentForNonNullParameter:OFF`.) I think we have also seen it _without_ Error Prone, as demonstrated in a simplified example in https://github.com/jspecify/jspecify/issues/50#issuecomment-520468335 (and maybe seen other times, like in https://github.com/jspecify/jspecify/issues/245#issuecomment-1122489647 or in a report by @SimY4 or others), but I'm not sure of the exact circumstances required to trigger it. My guess would be that:
- When you use an affected version of Error Prone, you can see the warning even for annotations _used only your dependencies_.
- When you don't use an affected version of Error Prone, you can see the warning only if _you use `@NullMarked` in the code you're compiling with `--release 8`_.

**Comment by SimY4** [comment]
@cpovirk 

TBH, this problem could be

**Comment by sdavids** [comment]
This still can be reproduced:

```shell
$ mkdir -p /tmp/test/example && cd "$_/.."
$ echo 'java=21.0.4-tem' > .sdkmanrc && sdk env
$ printf '@NullMarked\npackage example;\nimport org.jspecify.annotations.NullMarked;\n' > example/package-info.java
$ EP_VERSION=2.30.0
$ DATAFLOW_VERSION=3.41.0-eisop1
$ JSPECIFY_VERSION=1.0.0
$ curl -L -O -s https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/${EP_VERSION?}/error_prone_core-${EP_VERSION?}-with-dependencies.jar
$ curl -L -O -s https://repo1.maven.org/maven2/io/github/eisop/dataflow-errorprone/${DATAFLOW_VERSION?}/dataflow-errorprone-${DATAFLOW_VERSION?}.jar
$ curl -L -O -s https://repo1.maven.org/maven2/org/jspecify/jspecify/${JSPECIFY_VERSION?}/jspecify-${JSPECIFY_VERSION?}.jar
$ javac \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  -J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
  -J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
  -XDcompilePolicy=simple \
  --release 8 \
  -Xlint:-options \
  -Werror \
  -cp jspecify-${JSPECIFY_VERSION?}.jar \
  -processorpath error_prone_core-${EP_VERSION?}-with-dependencies.jar:dataflow-errorprone-${DATAFLOW_VERSION?}.jar \
  '-Xplugin:ErrorProne' \
  example/package-info.java
warning: unknown enum constant ElementType.MODULE
warning: unknown enum constant ElementType.MODULE
error: warnings found and -Werror specified
1 error
2 warnings
```

**Comment by cpovirk** [comment]
Thanks for the easy repro instructions! I should really get around to testing all [my guesses from July](https://github.com/jspecify/jspecify/issues/302#issuecomment-2225976703)....

It looks like the problem reproduces even without Error Prone, so I think this one falls under:

> When you don't use an affected version of Error Prone, you can see the warning only if you use `@NullMarked` in the code you're compiling with `--release 8`.

We haven't found any way to avoid that error without breaking support for using `@NullMarked` on modules (even if we use multi-release jars), so all we've got is workarounds. You can drop `-Werror` for the build that contains `package-info`. Or, if you can compile `package-info` separately from the rest of your files, you can keep `-Werror` but use `-source 8 -target 8` instead of `--release 8` for it. (That is very likely to be safe in practice, but it's not fully safe.) For a `--release 8`/`-source 8` build, it _might_ be possible to substitute in a Java 9+ copy of `javax.lang.model.element.ElementKind` during the build, but I haven't tried that. (Or you could make your own copy of the JSpecify annotation if you have that level of control over your build....)

The long-term hope is of course that Java 8 usage will continue to shrink. Given the choice between better Java 8 support and better Java 9+ support, we went with the latter, but it's been frustrating that we had to make that choice.

**Comment by sdavids** [comment]
Would a separate `jspecify-jdk8` artifact not suffice?—This has been mentioned several times…

**Comment by cpovirk** [comment]
There unfortunately is no particularly user-friendly way to ensure that the artifact that users want is the one that ends up appearing first on the classpath in general. And even if the right one ends up first, tools sometimes report errors when different versions of a class exists in multiple jars on the classpath.

Given that, the approach could work well for users who exclusively use the Java 8 version, but it would introduce those potential problems for users who use a mix of that and the Java 9+ version.

**Comment by sdavids** [comment]
Would it no be a similar situation to https://github.com/google/guava/pull/3683

**Comment by cpovirk** [comment]
Yes, but based on how that's gone, it's not a situation that I'm overly comfortable with: We've been kind of lost in helping users who have run into problems. Additionally, that helps only users of Gradle.

**Comment by cushon** [comment]
I was curious what the jetbrains numbers for Java 8 usage looked like historically, according to their survey it peaked in 2018 and the decrease in usage has been accelerating.

I am curious how common using `-Werror` is in general, but my sense is that there are enough javac diagnostics that can't be selectively disabled that using `-Werror` is challenging for many projects.

| Year  | Usage |
| ------------- | ------------- |
| 2023  | [50%](https://www.jetbrains.com/lp/devecosystem-2023/java/#java_versions)  |
| 2022  | [60%](https://www.jetbrains.com/lp/devecosystem-2022/java/#java_versions)  |
| 2021  | [72%](https://www.jetbrains.com/lp/devecosystem-2021/java/#java_versions)  |
| 2020  | [75%](https://www.jetbrains.com/lp/devecosystem-2020/java/#java_versions)  |
| 2019  | [83%](https://www.jetbrains.com/lp/devecosystem-2019/java/#java_versions)  |
| 2018  | [84%](https://www.jetbrains.com/research/devecosystem-2017/java/)  |
| 2017  | [79%](https://www.jetbrains.com/research/devecosystem-2017/java/)  |

**Comment by cpovirk** [comment]
Thanks for letting us know. It sounds like you were seeing the ["warning: unknown enum constant ElementType.MODULE"](https://github.com/jspecify/jspecify/wiki/version-compatibility#issues-with-newer-versions-of-javac-and---release-8) message (which appears with `--release 8`), which then failed your build because of `-Werror`, and not the outright [_crash_](https://github.com/jspecify/jspecify/wiki/version-compatibility#compile-time) ("unrecognized Attribute name MODULE") that happens when trying to build with a javac binary from JDK 8, right?

(I hope that we end up seeing enough usage of `@NullMarked` at the module level to justify this annoyance for people who support Java 8 :\\)
